#!/usr/bin/env bash
#
# Foundry · one-time VM setup. Runs AS ROOT on the VM, via deploy.sh --bootstrap.
#
# Idempotent: re-running is safe and is the intended way to re-apply hardening
# after an Ubuntu upgrade or a manual change.
set -euo pipefail

ok() { printf '    \033[0;32m✓\033[0m %s\n' "$*"; }

export DEBIAN_FRONTEND=noninteractive

# ─── Packages ───────────────────────────────────────────────────────
apt-get update -qq
apt-get upgrade -y -qq
apt-get install -y -qq python3.12-venv nginx fail2ban unattended-upgrades rsync curl
ok "packages installed"

# Security patches apply themselves. Kernel updates still need a reboot —
# that stays a monthly manual job, and it is the standing cost of running a
# VM rather than a managed host.
cat > /etc/apt/apt.conf.d/20auto-upgrades <<'EOF'
APT::Periodic::Update-Package-Lists "1";
APT::Periodic::Unattended-Upgrade "1";
EOF
systemctl enable --now unattended-upgrades >/dev/null 2>&1 || true
ok "unattended-upgrades enabled"

# ─── Service user ───────────────────────────────────────────────────
# No shell and no home: if the gateway process is ever compromised, the
# account it runs as cannot be logged into.
if ! id foundry >/dev/null 2>&1; then
  useradd -r -s /usr/sbin/nologin -d /opt/foundry foundry
fi
mkdir -p /opt/foundry/app /etc/foundry
chown -R foundry:foundry /opt/foundry
ok "service user and directories"

# ─── Secrets ────────────────────────────────────────────────────────
# Generated here, once, and never regenerated by a re-run — rotating these
# silently would break every in-flight upload ticket and desynchronise the
# gateway from Vercel until someone noticed.
#
# No Azure credentials live in this file. The VM's managed identity carries
# Storage Blob Data Contributor and DefaultAzureCredential reads it from the
# instance metadata endpoint, so there are no storage secrets on disk at all.
if [ ! -f /etc/foundry/gateway.env ]; then
  cat > /etc/foundry/gateway.env <<EOF
UPLOAD_TICKET_SECRET=$(openssl rand -base64 48)
SERVICE_TOKEN=$(openssl rand -base64 48)
AZURE_STORAGE_ACCOUNT=CHANGE_ME
AZURE_BLOB_CONTAINER=post-images
ALLOWED_ORIGINS=https://www.imperialentrepreneurs.com
MAX_UPLOAD_BYTES=8388608
EOF
  chown foundry:foundry /etc/foundry/gateway.env
  chmod 600 /etc/foundry/gateway.env
  ok "generated /etc/foundry/gateway.env"
  echo
  echo "    ACTION REQUIRED — set AZURE_STORAGE_ACCOUNT, then copy the two"
  echo "    secrets into Vercel (UPLOAD_TICKET_SECRET, and SERVICE_TOKEN as"
  echo "    GATEWAY_SERVICE_TOKEN):"
  echo
  sed 's/^/        /' /etc/foundry/gateway.env
  echo
else
  ok "/etc/foundry/gateway.env already exists — left alone"
fi

# ─── SSH hardening ──────────────────────────────────────────────────
# A drop-in rather than editing sshd_config, so an Ubuntu upgrade replacing
# the main file does not silently undo this.
cat > /etc/ssh/sshd_config.d/10-foundry.conf <<'EOF'
PasswordAuthentication no
PermitRootLogin no
KbdInteractiveAuthentication no
EOF
if sshd -t 2>/dev/null; then
  systemctl reload ssh 2>/dev/null || systemctl reload sshd 2>/dev/null || true
  ok "SSH: keys only, no root login"
else
  echo "    ! sshd config invalid — removing the drop-in rather than locking you out" >&2
  rm -f /etc/ssh/sshd_config.d/10-foundry.conf
fi

# ─── TLS material ───────────────────────────────────────────────────
mkdir -p /etc/ssl/cloudflare
chmod 700 /etc/ssl/cloudflare
if [ ! -f /etc/ssl/cloudflare/origin.pem ]; then
  echo
  echo "    ACTION REQUIRED — Cloudflare origin certificate not installed."
  echo "    Cloudflare → SSL/TLS → Origin Server → Create Certificate, then:"
  echo "        sudo nano /etc/ssl/cloudflare/origin.pem   # the certificate"
  echo "        sudo nano /etc/ssl/cloudflare/origin.key   # the private key"
  echo "        sudo chmod 600 /etc/ssl/cloudflare/origin.key"
  echo "    nginx will not start until both exist."
  echo
else
  ok "Cloudflare origin certificate present"
fi

ok "bootstrap complete"
