#!/usr/bin/env bash
#
# Foundry · one-time VM setup. Runs AS ROOT on the VM, via deploy.sh --bootstrap.
#
# Idempotent: re-running is safe and is the intended way to re-apply hardening
# after an Ubuntu upgrade or a manual change.
set -euo pipefail

ok() { printf '    \033[0;32m✓\033[0m %s\n' "$*"; }

export DEBIAN_FRONTEND=noninteractive

# ─── Packages ───────────────────────────────────────────────────────
# No python3.12-venv or rsync here anymore: the gateway runs from a
# container now, so Python never runs on the host, and deploy.sh ships code
# by pushing/pulling an image rather than rsyncing source.
apt-get update -qq
apt-get upgrade -y -qq
apt-get install -y -qq nginx fail2ban unattended-upgrades curl gnupg
ok "packages installed"

# ─── Docker ─────────────────────────────────────────────────────────
if ! command -v docker >/dev/null 2>&1; then
  install -m 0755 -d /etc/apt/keyrings
  curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  chmod a+r /etc/apt/keyrings/docker.gpg
  echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo "$VERSION_CODENAME") stable" \
    > /etc/apt/sources.list.d/docker.list
  apt-get update -qq
  apt-get install -y -qq docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
  systemctl enable --now docker >/dev/null 2>&1
  ok "docker installed"
else
  ok "docker already installed"
fi

# Security patches apply themselves. Kernel updates still need a reboot —
# that stays a monthly manual job, and it is the standing cost of running a
# VM rather than a managed host.
cat > /etc/apt/apt.conf.d/20auto-upgrades <<'EOF'
APT::Periodic::Update-Package-Lists "1";
APT::Periodic::Unattended-Upgrade "1";
EOF
systemctl enable --now unattended-upgrades >/dev/null 2>&1 || true
ok "unattended-upgrades enabled"

# ─── Secrets ────────────────────────────────────────────────────────
# No dedicated `foundry` service user anymore: the gateway process itself
# now runs as the non-root `gateway` user baked into the image
# (server/Dockerfile), sandboxed by Docker rather than by a host account.
# systemd runs `docker` as root — see infra/vm/foundry-gateway.service for
# why that's the right tradeoff — so nothing on the host needs to own this
# file except root.
#
# Generated here, once, and never regenerated by a re-run — rotating these
# silently would break every in-flight upload ticket and desynchronise the
# gateway from Vercel until someone noticed.
#
# No Azure credentials live in this file. The VM's managed identity carries
# Storage Blob Data Contributor and DefaultAzureCredential reads it from the
# instance metadata endpoint, so there are no storage secrets on disk at all.
mkdir -p /etc/foundry
if [ ! -f /etc/foundry/gateway.env ]; then
  cat > /etc/foundry/gateway.env <<EOF
UPLOAD_TICKET_SECRET=$(openssl rand -base64 48)
SERVICE_TOKEN=$(openssl rand -base64 48)
AZURE_STORAGE_ACCOUNT=CHANGE_ME
AZURE_BLOB_CONTAINER=post-images
ALLOWED_ORIGINS=https://www.imperialentrepreneurs.com
MAX_UPLOAD_BYTES=8388608
EOF
  chmod 600 /etc/foundry/gateway.env
  ok "generated /etc/foundry/gateway.env"
  echo
  echo "    ACTION REQUIRED — set AZURE_STORAGE_ACCOUNT, then copy the two"
  echo "    secrets into Vercel (UPLOAD_TICKET_SECRET, and SERVICE_TOKEN as"
  echo "    GATEWAY_SERVICE_TOKEN):"
  echo
  sed 's/^/        /' /etc/foundry/gateway.env
  echo
else
  ok "/etc/foundry/gateway.env already exists — left alone"
fi

# ─── GHCR pull credential ───────────────────────────────────────────
# The org's package visibility can't be set to public — that setting is
# locked by policy above the org level, confirmed even an actual Owner
# account can't override it (2026-08-31). So the image stays private and
# this VM authenticates its own pulls instead, same idea as the Vercel
# service principal being read-only: least privilege beats "public but
# nothing sensitive in it" when private is free to keep.
#
# Not generated here — this has to be a GitHub personal access token
# (read:packages only), and there is no API for scripting your own token
# creation, by GitHub's own design. A human makes this at
# github.com/settings/tokens and drops it here by hand.
if [ ! -f /etc/foundry/ghcr-pull.env ]; then
  echo
  echo "    ACTION REQUIRED — GHCR pull credential not installed."
  echo "    github.com/settings/tokens → Generate new token (classic) →"
  echo "    scope: read:packages only. Then:"
  echo "        sudo tee /etc/foundry/ghcr-pull.env <<EOF"
  echo "        GHCR_USERNAME=<your github username>"
  echo "        GHCR_TOKEN=<the token>"
  echo "        EOF"
  echo "        sudo chmod 600 /etc/foundry/ghcr-pull.env"
  echo "    The gateway will not start until this exists — its image is"
  echo "    private and docker pull needs to authenticate."
  echo
else
  chmod 600 /etc/foundry/ghcr-pull.env
  ok "/etc/foundry/ghcr-pull.env already exists — left alone"
fi

# ─── SSH hardening ──────────────────────────────────────────────────
# A drop-in rather than editing sshd_config, so an Ubuntu upgrade replacing
# the main file does not silently undo this.
cat > /etc/ssh/sshd_config.d/10-foundry.conf <<'EOF'
PasswordAuthentication no
PermitRootLogin no
KbdInteractiveAuthentication no
EOF
if sshd -t 2>/dev/null; then
  systemctl reload ssh 2>/dev/null || systemctl reload sshd 2>/dev/null || true
  ok "SSH: keys only, no root login"
else
  echo "    ! sshd config invalid — removing the drop-in rather than locking you out" >&2
  rm -f /etc/ssh/sshd_config.d/10-foundry.conf
fi

# ─── TLS material ───────────────────────────────────────────────────
mkdir -p /etc/ssl/cloudflare
chmod 700 /etc/ssl/cloudflare
if [ ! -f /etc/ssl/cloudflare/origin.pem ]; then
  echo
  echo "    ACTION REQUIRED — Cloudflare origin certificate not installed."
  echo "    Cloudflare → SSL/TLS → Origin Server → Create Certificate, then:"
  echo "        sudo nano /etc/ssl/cloudflare/origin.pem   # the certificate"
  echo "        sudo nano /etc/ssl/cloudflare/origin.key   # the private key"
  echo "        sudo chmod 600 /etc/ssl/cloudflare/origin.key"
  echo "    nginx will not start until both exist."
  echo
else
  ok "Cloudflare origin certificate present"
fi

ok "bootstrap complete"
