import { z } from "zod";
import { ok, err, type Result } from "@/lib/result";

// ════════════════════════════════════════════════════════════════════
// Foundry · Community post validation
//
// Shared by the composer and the server action, for the reason
// lib/validation/fields.ts records: when the client and server validate
// with different rules, the drift shows up as a form that submits and
// then fails for no visible reason.
//
// Lengths are enforced at four layers, deliberately, matching the
// listings: maxLength on the input, this schema, the column CHECK, and a
// human sentence in CHECK_CONSTRAINT_MESSAGES so a bypass still reads.
// ════════════════════════════════════════════════════════════════════

export const POST_TITLE_MAX = 120;
export const POST_BODY_MAX = 3000;
export const POST_BODY_MIN = 10;
export const POST_ALT_MAX = 200;
export const POST_MAX_IMAGES = 2;

// 10 characters, not 1. The column allows 1 because a constraint should
// not encode editorial policy, but "hi" is not a post and a floor here is
// the cheapest spam filter there is — it costs a real member nothing and
// makes the laziest kind of noise impossible.
export const postSchema = z.object({
  title: z
    .string()
    .trim()
    .min(3, "Title must be at least 3 characters.")
    .max(POST_TITLE_MAX, `Title must be ${POST_TITLE_MAX} characters or fewer.`),
  body: z
    .string()
    .trim()
    .min(POST_BODY_MIN, `Write at least ${POST_BODY_MIN} characters.`)
    .max(POST_BODY_MAX, `Post must be ${POST_BODY_MAX} characters or fewer.`),
  images: z
    .array(
      z.object({
        // Generated by issue_upload_ticket, never by the client. The shape
        // is asserted here too so a malformed key never reaches the RPC.
        blob_key: z
          .string()
          .regex(/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\.webp$/,
            "That image is no longer valid — please re-attach it."),
        alt_text: z
          .string()
          .trim()
          .min(1, "Describe the image so members using a screen reader can follow.")
          .max(POST_ALT_MAX, `Description must be ${POST_ALT_MAX} characters or fewer.`),
        width: z.number().int().positive().max(8000),
        height: z.number().int().positive().max(8000),
        byte_size: z.number().int().positive().max(8 * 1024 * 1024),
      }),
    )
    .max(POST_MAX_IMAGES, `A post can have at most ${POST_MAX_IMAGES} images.`)
    .default([]),
});

export type PostPayload = z.infer<typeof postSchema>;

export const REPORT_CATEGORIES = [
  { value: "illegal", label: "Illegal content" },
  { value: "harassment", label: "Harassment or bullying" },
  { value: "hate", label: "Hate speech" },
  { value: "sexual", label: "Sexual or explicit content" },
  { value: "spam", label: "Spam or advertising" },
  { value: "misinformation", label: "Misinformation" },
  { value: "other", label: "Something else" },
] as const;

export const reportSchema = z.object({
  postId: z.uuid("That post no longer exists."),
  category: z.enum(
    REPORT_CATEGORIES.map((c) => c.value) as [string, ...string[]],
    "Choose a reason.",
  ),
  reason: z
    .string()
    .trim()
    .min(10, "Tell us a little more so an admin can act on this.")
    .max(1000, "Please keep this to 1000 characters or fewer."),
});

export type ReportPayload = z.infer<typeof reportSchema>;

// Matches validate() in lib/validation/listings.ts — returns a Result so a
// caller can `if (!parsed.ok) return parsed;` straight into its own
// signature.
export function validatePost<T>(schema: z.ZodType<T>, input: unknown): Result<T> {
  const res = schema.safeParse(input);
  if (!res.success) return err(res.error.issues[0]?.message ?? "Invalid input.");
  return ok(res.data) as Result<T>;
}

// ─── Link rendering ─────────────────────────────────────────────────
// Post bodies are plain text and are rendered as text; this is the only
// thing that turns any part of one into a link, so it is the only place
// the scheme rules have to hold.
//
// Two rules, both load-bearing:
//
//   1. http and https ONLY. This is the line that stops `javascript:` and
//      `data:` URLs — the classic way a "harmless" text field becomes an
//      XSS vector the moment someone linkifies it.
//   2. The real hostname is returned alongside, so the UI can display it.
//      A link whose text claims one destination and whose href goes
//      somewhere else is the whole mechanic of a phishing post, and on a
//      platform carrying Imperial's name a fake login page is the
//      realistic version of that attack.
//
// Anything not matching is left as plain text. Failing to a non-link is
// always safe; failing to a link is not.

const URL_PATTERN = /\bhttps?:\/\/[^\s<>"']+/gi;

export type PostSegment =
  | { kind: "text"; text: string }
  | { kind: "link"; href: string; host: string };

export function segmentPostBody(body: string): PostSegment[] {
  const segments: PostSegment[] = [];
  let cursor = 0;

  for (const match of body.matchAll(URL_PATTERN)) {
    const raw = match[0];
    const start = match.index ?? 0;

    // Trailing punctuation is almost always sentence punctuation rather
    // than part of the URL ("see https://x.com." / "(https://x.com)").
    const trimmed = raw.replace(/[.,;:!?)\]}]+$/, "");

    let host: string | null = null;
    try {
      const url = new URL(trimmed);
      // Re-checked after parsing, not just by the regex. `new URL` is what
      // the browser will act on, so it is what has to be interrogated.
      if (url.protocol === "http:" || url.protocol === "https:") host = url.hostname;
    } catch {
      host = null;
    }

    if (start > cursor) segments.push({ kind: "text", text: body.slice(cursor, start) });

    if (host) {
      segments.push({ kind: "link", href: trimmed, host });
      cursor = start + trimmed.length;
    } else {
      segments.push({ kind: "text", text: raw });
      cursor = start + raw.length;
    }
  }

  if (cursor < body.length) segments.push({ kind: "text", text: body.slice(cursor) });
  return segments;
}
