"""Ticket and service-token verification.

The gateway has no database and no idea what a Foundry member is. It trusts
exactly one thing: a short-lived HS256 ticket minted by the Next.js app,
which decided that this member is approved, within their rate limit, and
entitled to write to this one blob key.

That split is deliberate. Authorisation stays in one place, with the guards
that already exist, while image bytes never pass through the web tier — and
because the token format is ours rather than Supabase's, moving the app to a
different identity provider does not touch this file.
"""

from __future__ import annotations

import hmac
import re
from dataclasses import dataclass

import jwt

from .config import settings


class InvalidTicket(Exception):
    """The ticket is absent, malformed, expired, or not ours."""


# Keys are generated by issue_upload_ticket as uuid4 + ".webp". Validated
# again here because a value out of a token becomes a path component, and a
# path component must never be trusted on the word of its signer alone —
# defence in depth against a compromised signing key.
_KEY_PATTERN = re.compile(
    r"^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\.webp$"
)


@dataclass(frozen=True)
class Ticket:
    sub: str
    key: str
    purpose: str
    max_bytes: int


def _bearer(header: str | None) -> str:
    if not header or not header.startswith("Bearer "):
        raise InvalidTicket("Missing bearer token")
    return header[len("Bearer ") :].strip()


def verify_ticket(authorization: str | None) -> Ticket:
    token = _bearer(authorization)

    try:
        # algorithms is pinned to a single value. Leaving it open is the
        # algorithm-confusion bug — a forged token declaring "alg": "none",
        # or an RS256 token verified with the public key as an HMAC secret.
        claims = jwt.decode(
            token,
            settings().upload_ticket_secret,
            algorithms=["HS256"],
            options={"require": ["exp", "sub"]},
        )
    except jwt.PyJWTError as exc:
        raise InvalidTicket("Ticket is invalid or has expired") from exc

    key = claims.get("key", "")
    if not isinstance(key, str) or not _KEY_PATTERN.match(key):
        raise InvalidTicket("Ticket names an unacceptable object key")

    if claims.get("purpose") != "post_image":
        raise InvalidTicket("Ticket is not valid for image upload")

    max_bytes = claims.get("max_bytes")
    if not isinstance(max_bytes, int) or max_bytes <= 0:
        raise InvalidTicket("Ticket does not carry a size limit")

    # The ticket cannot raise its own ceiling above the server's.
    return Ticket(
        sub=str(claims["sub"]),
        key=key,
        purpose="post_image",
        max_bytes=min(max_bytes, settings().max_upload_bytes),
    )


def verify_service_token(authorization: str | None) -> None:
    """Authenticate the deletion drain, which is service-to-service.

    Constant-time comparison: a plain `==` leaks the shared secret one
    character at a time to anyone able to measure the response.
    """
    token = _bearer(authorization)
    if not hmac.compare_digest(token, settings().service_token):
        raise InvalidTicket("Invalid service token")
