"""Ticket and service-token verification.

The gateway has no database and no idea what a Foundry member is. It trusts
exactly one thing: a short-lived HS256 ticket minted by the Next.js app,
which decided that this member is approved, within their rate limit, and
entitled to write to this one blob key.

That split is deliberate. Authorisation stays in one place, with the guards
that already exist, while image and document bytes never pass through the
web tier — and because the token format is ours rather than Supabase's,
moving the app to a different identity provider does not touch this file.
"""

from __future__ import annotations

import hmac
import re
from dataclasses import dataclass
from typing import Literal

import jwt

from .config import settings

TicketPurpose = Literal["post_image", "profile_picture", "cv"]


class InvalidTicket(Exception):
    """The ticket is absent, malformed, expired, or not ours."""


# Keys are generated by issue_upload_ticket (Postgres, 20260901000008) as
# uuid4 + an extension chosen by purpose. Validated again here because a
# value out of a token becomes a path component, and a path component must
# never be trusted on the word of its signer alone — defence in depth
# against a compromised signing key.
#
# post_image and profile_picture both end '.webp': the gateway always
# re-encodes to WebP regardless of what was uploaded (images.py), so the
# key names the OUTPUT format, not the input.
#
# cv ends '.cv' — a made-up, meaningless suffix. A CV's real format (PDF or
# DOCX) isn't known until the bytes are sniffed, which happens strictly
# after the ticket is issued, so the key cannot encode it. The suffix
# exists only so this regex has something fixed to check; the real
# Content-Type is set at write time from sniffed magic bytes
# (documents.py), and the filename a browser saves under comes from
# cv_original_filename via Content-Disposition — neither depends on this.
_UUID = r"[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}"
_IMAGE_KEY_PATTERN = re.compile(rf"^{_UUID}\.webp$")
_DOCUMENT_KEY_PATTERN = re.compile(rf"^{_UUID}\.cv$")

_KEY_PATTERN_FOR_PURPOSE: dict[TicketPurpose, re.Pattern[str]] = {
    "post_image": _IMAGE_KEY_PATTERN,
    "profile_picture": _IMAGE_KEY_PATTERN,
    "cv": _DOCUMENT_KEY_PATTERN,
}


def is_valid_key(key: object, purpose: TicketPurpose) -> bool:
    """True when `key` is a blob key this service is willing to touch for
    this purpose.

    Used on both the upload and delete paths. A key is always a path
    component by the time it reaches Azure, and the rule is that a path
    component is never trusted on the word of whoever sent it — not the
    ticket signer, and not the holder of the service token either.
    """
    if not isinstance(key, str):
        return False
    return _KEY_PATTERN_FOR_PURPOSE[purpose].match(key) is not None


@dataclass(frozen=True)
class Ticket:
    sub: str
    key: str
    purpose: TicketPurpose
    max_bytes: int
    container: str


def _bearer(header: str | None) -> str:
    if not header or not header.startswith("Bearer "):
        raise InvalidTicket("Missing bearer token")
    return header[len("Bearer ") :].strip()


def verify_ticket(authorization: str | None) -> Ticket:
    token = _bearer(authorization)

    try:
        # algorithms is pinned to a single value. Leaving it open is the
        # algorithm-confusion bug — a forged token declaring "alg": "none",
        # or an RS256 token verified with the public key as an HMAC secret.
        claims = jwt.decode(
            token,
            settings().upload_ticket_secret,
            algorithms=["HS256"],
            options={"require": ["exp", "sub"]},
        )
    except jwt.PyJWTError as exc:
        raise InvalidTicket("Ticket is invalid or has expired") from exc

    purpose = claims.get("purpose")
    if purpose not in ("post_image", "profile_picture", "cv"):
        raise InvalidTicket("Ticket is not valid for any known upload purpose")

    key = claims.get("key", "")
    if not is_valid_key(key, purpose):
        raise InvalidTicket("Ticket names an unacceptable object key")

    max_bytes = claims.get("max_bytes")
    if not isinstance(max_bytes, int) or max_bytes <= 0:
        raise InvalidTicket("Ticket does not carry a size limit")

    # The ticket cannot raise its own ceiling above the server's. CVs get
    # their own, separate cap — see config.max_document_bytes.
    server_cap = (
        settings().max_document_bytes if purpose == "cv" else settings().max_upload_bytes
    )

    return Ticket(
        sub=str(claims["sub"]),
        key=key,
        purpose=purpose,
        max_bytes=min(max_bytes, server_cap),
        container=settings().containers[purpose],
    )


def verify_service_token(authorization: str | None) -> None:
    """Authenticate the deletion drain, which is service-to-service.

    Constant-time comparison: a plain `==` leaks the shared secret one
    character at a time to anyone able to measure the response.
    """
    token = _bearer(authorization)
    if not hmac.compare_digest(token, settings().service_token):
        raise InvalidTicket("Invalid service token")
